//! SDK generation from the live registry.
//!
//! The generated clients are thin typed wrappers over the MCP tool surface;
//! they do not reimplement any calculation.

use bicmath_core::schema::{NumberKind, ValueSchema};
use bicmath_engine::Engine;

fn ts_type(schema: &ValueSchema) -> String {
    match schema {
        ValueSchema::Number { kind } => match kind {
            NumberKind::Float64 => "ExactNumber | number".to_string(),
            _ => "ExactNumber | number | string".to_string(),
        },
        ValueSchema::Bool => "boolean".to_string(),
        ValueSchema::Text { .. } => "string".to_string(),
        ValueSchema::Enum { variants } => variants
            .iter()
            .map(|variant| format!("\"{variant}\""))
            .collect::<Vec<_>>()
            .join(" | "),
        ValueSchema::Array { items, .. } => format!("Array<{}>", ts_type(items)),
        ValueSchema::Record {
            fields,
            allow_extra,
        } => {
            let mut parts = Vec::new();
            for field in fields {
                let optional = if field.required { "" } else { "?" };
                parts.push(format!(
                    "{}{}: {}",
                    field.name,
                    optional,
                    ts_type(&field.schema)
                ));
            }
            if *allow_extra {
                parts.push("[key: string]: unknown".to_string());
            }
            format!("{{ {} }}", parts.join("; "))
        }
        ValueSchema::Quantity { .. } => "Quantity".to_string(),
        ValueSchema::Money => "Money".to_string(),
        ValueSchema::Matrix { .. } => "Matrix".to_string(),
        ValueSchema::Expression { .. } => "string".to_string(),
        ValueSchema::Bound => "Bound".to_string(),
        ValueSchema::Any => "unknown".to_string(),
    }
}

fn ts_arguments(engine: &Engine, function: &str) -> String {
    match engine
        .registry()
        .function_descriptors()
        .find(|descriptor| descriptor.id == function)
    {
        Some(descriptor) => {
            let mut parts = Vec::new();
            for param in &descriptor.parameters {
                let optional = if param.required { "" } else { "?" };
                parts.push(format!(
                    "{}{}: {}",
                    param.name,
                    optional,
                    ts_type(&param.schema)
                ));
            }
            format!("{{ {} }}", parts.join("; "))
        }
        None => "Record<string, unknown>".to_string(),
    }
}

fn ts_result(engine: &Engine, function: &str) -> String {
    match engine
        .registry()
        .function_descriptors()
        .find(|descriptor| descriptor.id == function)
    {
        Some(descriptor) => ts_type(&descriptor.output),
        None => "unknown".to_string(),
    }
}

/// Generate a TypeScript client from the registry.
pub fn generate_typescript(engine: &Engine) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `bicmath sdk --language typescript`. Do not edit by hand.\n\
         // Exact values are strings in the canonical wire format and never JS numbers.\n\n",
    );
    out.push_str(
        "export type ExactNumber =\n\
         \x20 | { kind: \"integer\"; value: string }\n\
         \x20 | { kind: \"decimal\"; value: string }\n\
         \x20 | { kind: \"rational\"; numerator: string; denominator: string }\n\
         \x20 | { kind: \"float64\"; value: string };\n\n\
         export interface Quantity { kind: \"quantity\"; value: ExactNumber | number; dimension: Record<string, number>; }\n\
         export interface Money { kind: \"money\"; amount: ExactNumber | number; currency: string; }\n\
         export interface Matrix { kind: \"matrix\"; rows: number; cols: number; data: Array<ExactNumber | number>; }\n\
         export type Bound = { kind: \"bound\"; unbounded: true } | { kind: \"bound\"; value: ExactNumber | number };\n\n\
         export interface ResultEnvelope<T = unknown> {\n\
         \x20 schema_version: number;\n\
         \x20 function?: { id: string; version: string };\n\
         \x20 engine: { name: string; version: string; build?: string; modules: Record<string, string> };\n\
         \x20 result: T;\n\
         \x20 exactness: \"exact\" | \"rounded\" | \"approximate\";\n\
         \x20 context: unknown;\n\
         \x20 error_estimate?: unknown;\n\
         \x20 warnings?: Array<{ code: string; message: string }>;\n\
         \x20 assumptions?: Array<{ id: string; statement: string; source: string }>;\n\
         \x20 fingerprint: string;\n\
         \x20 receipt?: unknown;\n\
         \x20 trace?: unknown;\n\
         }\n\n\
         export interface ErrorResponse {\n\
         \x20 schema_version: number;\n\
         \x20 error: { code: string; message: string; path?: string; details?: unknown };\n\
         }\n\n\
         export interface ContextOverrides {\n\
         \x20 mode?: \"exact\" | \"auto\" | \"scientific\";\n\
         \x20 budget?: \"fast\" | \"balanced\" | \"precise\";\n\
         \x20 precision?: number;\n\
         \x20 rounding?: \"half_even\" | \"half_away_from_zero\" | \"toward_zero\" | \"floor\" | \"ceiling\";\n\
         \x20 seed?: number;\n\
         \x20 limits?: Record<string, number>;\n\
         }\n\n",
    );
    out.push_str("export interface FunctionSchemas {\n");
    let mut descriptors: Vec<_> = engine.registry().function_descriptors().collect();
    descriptors.sort_by(|a, b| a.id.cmp(&b.id));
    for descriptor in &descriptors {
        out.push_str(&format!(
            "  \"{}\": {{ arguments: {}; result: {} }};\n",
            descriptor.id,
            ts_arguments(engine, &descriptor.id),
            ts_result(engine, &descriptor.id)
        ));
    }
    out.push_str("}\n\n");
    out.push_str(
        "export type FunctionId = keyof FunctionSchemas;\n\n\
         export interface ToolResult { structuredContent?: unknown; isError?: boolean; }\n\
         export interface BicMathTransport {\n\
         \x20 callTool(name: string, args: Record<string, unknown>): Promise<ToolResult>;\n\
         }\n\n\
         export class BicMathClient {\n\
         \x20 constructor(private readonly transport: BicMathTransport) {}\n\n\
         \x20 private async tool(name: string, args: Record<string, unknown>): Promise<unknown> {\n\
         \x20   const result = await this.transport.callTool(name, args);\n\
         \x20   if (result.isError) throw new Error(JSON.stringify(result.structuredContent));\n\
         \x20   return result.structuredContent;\n\
         \x20 }\n\n\
         \x20 async calculate<K extends FunctionId>(\n\
         \x20   functionId: K,\n\
         \x20   args: FunctionSchemas[K][\"arguments\"],\n\
         \x20   context?: ContextOverrides,\n\
         \x20   receipt = false,\n\
         \x20 ): Promise<ResultEnvelope<FunctionSchemas[K][\"result\"]>> {\n\
         \x20   return (await this.tool(\"calculate\", { function: functionId, arguments: args, context, receipt })) as ResultEnvelope<FunctionSchemas[K][\"result\"]>;\n\
         \x20 }\n\n\
         \x20 async evaluate(expression: string, bindings?: Record<string, unknown>, context?: ContextOverrides, receipt = false) {\n\
         \x20   return (await this.tool(\"evaluate\", { expression, bindings, context, receipt })) as ResultEnvelope;\n\
         \x20 }\n\n\
         \x20 async batch(nodes: Array<Record<string, unknown>>, outputs?: string[], failFast = true) {\n\
         \x20   return (await this.tool(\"batch\", { nodes, outputs, fail_fast: failFast })) as Record<string, unknown>;\n\
         \x20 }\n\n\
         \x20 async listModules() { return this.tool(\"list_modules\", {}); }\n\
         \x20 async listFunctions(filter: { module?: string; query?: string; offset?: number; limit?: number } = {}) {\n\
         \x20   return this.tool(\"list_functions\", filter);\n\
         \x20 }\n\
         \x20 async describeFunction(functionId: string) { return this.tool(\"describe_function\", { function: functionId }); }\n\
         }\n",
    );
    out
}

/// Generate a Python client from the registry.
pub fn generate_python(engine: &Engine) -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated by `bicmath sdk --language python`. Do not edit by hand.\n\
         # Exact values are strings in the canonical wire format; do not convert them to float.\n\n\
         from __future__ import annotations\n\n\
         from dataclasses import dataclass, field\n\
         from typing import Any, Callable, Mapping, Sequence\n\n\n\
         @dataclass\n\
         class ResultEnvelope:\n\
         \x20   schema_version: int\n\
         \x20   function: dict[str, str] | None\n\
         \x20   engine: dict[str, Any]\n\
         \x20   result: Any\n\
         \x20   exactness: str\n\
         \x20   context: dict[str, Any]\n\
         \x20   warnings: list[dict[str, Any]] = field(default_factory=list)\n\
         \x20   assumptions: list[dict[str, Any]] = field(default_factory=list)\n\
         \x20   fingerprint: str = \"\"\n\n\n\
         class BicMathError(RuntimeError):\n\
         \x20   \"\"\"Raised with the structured error body from the server.\"\"\"\n\n\n\
         class BicMathClient:\n\
         \x20   \"\"\"Thin typed wrapper over the BicMath MCP tools.\n\n\
         \x20   transport is any callable `(tool_name, arguments) -> dict` that speaks MCP\n\
         \x20   (for example an mcp client session). No calculation happens here.\n\
         \x20   \"\"\"\n\n\
         \x20   def __init__(self, transport: Callable[[str, Mapping[str, Any]], Mapping[str, Any]]) -> None:\n\
         \x20       self._transport = transport\n\n\
         \x20   def _tool(self, name: str, arguments: Mapping[str, Any]) -> Any:\n\
         \x20       result = self._transport(name, arguments)\n\
         \x20       if result.get(\"isError\"):\n\
         \x20           raise BicMathError(str(result.get(\"structuredContent\")))\n\
         \x20       return result.get(\"structuredContent\")\n\n\
         \x20   def calculate(self, function: str, arguments: Mapping[str, Any] | None = None,\n\
         \x20                 context: Mapping[str, Any] | None = None, receipt: bool = False) -> ResultEnvelope:\n\
         \x20       payload = self._tool(\"calculate\", {\n\
         \x20           \"function\": function, \"arguments\": dict(arguments or {}),\n\
         \x20           \"context\": context, \"receipt\": receipt})\n\
         \x20       return ResultEnvelope(**payload)\n\n\
         \x20   def evaluate(self, expression: str, bindings: Mapping[str, Any] | None = None,\n\
         \x20                context: Mapping[str, Any] | None = None, receipt: bool = False) -> ResultEnvelope:\n\
         \x20       payload = self._tool(\"evaluate\", {\n\
         \x20           \"expression\": expression, \"bindings\": dict(bindings or {}),\n\
         \x20           \"context\": context, \"receipt\": receipt})\n\
         \x20       return ResultEnvelope(**payload)\n\n\
         \x20   def batch(self, nodes: Sequence[Mapping[str, Any]], outputs: Sequence[str] | None = None,\n\
         \x20             fail_fast: bool = True) -> Any:\n\
         \x20       return self._tool(\"batch\", {\n\
         \x20           \"nodes\": list(nodes), \"outputs\": list(outputs) if outputs else None,\n\
         \x20           \"fail_fast\": fail_fast})\n\n\
         \x20   def list_modules(self) -> Any:\n\
         \x20       return self._tool(\"list_modules\", {})\n\n\
         \x20   def list_functions(self, module: str | None = None, query: str | None = None,\n\
         \x20                      offset: int = 0, limit: int = 50) -> Any:\n\
         \x20       return self._tool(\"list_functions\", {\n\
         \x20           \"module\": module, \"query\": query, \"offset\": offset, \"limit\": limit})\n\n\
         \x20   def describe_function(self, function: str) -> Any:\n\
         \x20       return self._tool(\"describe_function\", {\"function\": function})\n\n\n\
         # Function ids and their parameter names, generated from the registry.\n\
         FUNCTIONS: dict[str, tuple[str, ...]] = {\n",
    );
    let mut descriptors: Vec<_> = engine.registry().function_descriptors().collect();
    descriptors.sort_by(|a, b| a.id.cmp(&b.id));
    for descriptor in &descriptors {
        let params: Vec<String> = descriptor
            .parameters
            .iter()
            .map(|param| format!("\"{}\"", param.name))
            .collect();
        out.push_str(&format!(
            "    \"{}\": ({}),\n",
            descriptor.id,
            params.join(", ")
        ));
    }
    out.push_str("}\n");
    out
}
