[package]
name = "bicmath-interval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "BicMath interval module."

[dependencies]
bicmath-core.workspace = true
serde.workspace = true
serde_json.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-integer.workspace = true
num-traits.workspace = true
libm.workspace = true
