#!/usr/bin/env python3
"""Generate THIRD_PARTY_LICENSES.md from `cargo metadata` on stdin."""

import json
import sys

metadata = json.load(sys.stdin)
packages = {p["id"]: p for p in metadata["packages"]}
workspace = set(metadata["workspace_members"])
resolved = {node["id"] for node in metadata["resolve"]["nodes"]}

rows = []
for pid in resolved:
    if pid in workspace:
        continue
    package = packages[pid]
    rows.append(
        (
            package["name"],
            package["version"],
            package.get("license") or "UNKNOWN",
            package.get("repository") or "",
        )
    )

print("# Third-party licenses\n")
print(
    "Generated by `scripts/license-report.sh` from the resolved dependency graph. "
    "This project is MIT licensed; the crates below retain their own licenses.\n"
)
print("| Crate | Version | License | Repository |")
print("|---|---|---|---|")
for name, version, license_text, repository in sorted(rows):
    print(f"| {name} | {version} | {license_text} | {repository} |")
